### ISSUE TITLE
Is it possible to post to Steemit using this API?

### ISSUE THREAD

**Issue by BCwhoLikesPHP** [dragosroua/php-steem-tools#5]
I was wondering if it is possible to post to Steemit using this API and if so, what are the server requirements/dependencies?

**Comment by dragosroua** [comment]
Yes, in theory it would be possible to broadcast a transaction to the Steem blockchain with this tool, but I wouldn't advise, as this would mean the posting key would be stored on the server, which is not a secure practice.

**Comment by BCwhoLikesPHP** [comment]
Fair enough... but if I wanted to do it anyway, what would the server need? I have looked at another php library to do this specifically "t3ran13/php-graphene-node-client". That library requires  secp256k1 , secp256k1-php to be installed as well as GMP. I was wondering if this API could post to Steemit without the need of more specialized dependencies like that. The goal is to be able to run something I am testing on a very modest VPS running a vanilla version of centos web-panel LAMP stack or Webuzo LAMP stack. I want to see if I can get something running on the cheapest VPS with Free or nearly FRee web management software that is super easy to use and configure!

Let me know if you have any ideas or example code...

**Comment by dragosroua** [comment]
Again, I can't stress this loud enough: it's a non-recommended way to do it, as the key must stay on the machine used to perform the call. If you're willing to take that risk, I would start looking at these parts in SteemApi.php:

```
        public function broadcastTransaction ($params)
	{
			$result = $this->SteemLayer->call('broadcast_transaction', $params);
			return $result;
	}
	public function broadcastTransactionWithCallback ($params)
	{
			$result = $this->SteemLayer->call('broadcast_transaction_with_callback', $params);
			return $result;
	}
	public function broadcastTransactionSynchronous ($params)
	{
			$result = $this->SteemLayer->call('broadcast_transaction_synchronous', $params);
			return $result;
	}
```
In the same file, starting with line 813, there are few higher level operations that you can do on the blockchain, like voting, commenting, etc. Hope this helps.

**Comment by BCwhoLikesPHP** [comment]
It helps a great deal Thank you so much! Do you know anything about server requirements though? Any special libs needed to sign requests sent to the blockchain or anything? I'll just have to test and see.
